/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all active currencies with their spot price, spot price 24hrs ago.
 *
 * For real-time updates, recommend using Channels -> ticker or orderbook for real-time updates.
 */
export type PublicGetAllCurrencies = PublicGetAllCurrenciesJSONRPCSchema
export type Method = 'public/get_all_currencies'
/**
 * Underlying currency of asset (`ETH`, `BTC`, etc)
 */
export type Currency = string
/**
 * Spot price of the currency
 */
export type SpotPrice = string
/**
 * Spot price of the currency 24 hours ago
 */
export type SpotPrice_24H = string
export type Result = CurrencyResponseSchema[]

export interface PublicGetAllCurrenciesJSONRPCSchema {
  request: PublicGetAllCurrenciesRequestSchema
  response: PublicGetAllCurrenciesResponseSchema
}
export interface PublicGetAllCurrenciesRequestSchema {
  id?: string | number
  method: Method
  params: PublicGetAllCurrenciesParamsSchema
}
export interface PublicGetAllCurrenciesParamsSchema {}
export interface PublicGetAllCurrenciesResponseSchema {
  id: string | number
  result: Result
}
export interface CurrencyResponseSchema {
  currency: Currency
  spot_price: SpotPrice
  spot_price_24h: SpotPrice_24H
}
